In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
data = pd.read_csv('churn.csv')
data

,Unnamed: 0,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,Gift Vouchers/Coupons,...,300.630000,53005.25,17.0,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,0
1,1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,Gift Vouchers/Coupons,...,306.340000,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,0
2,2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,...,516.160000,21027.00,22.0,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,1
3,3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,...,53.270000,25239.56,6.0,567.660000,No,Yes,Yes,Unsolved,Poor Website,1
4,4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,Credit/Debit Card Offers,...,113.130000,24483.66,16.0,663.060000,No,Yes,Yes,Solved,Poor Website,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36987,36987,46,F,6F51HFO,NaN,Basic Membership,2017-09-21,No,xxxxxxxx,Credit/Debit Card Offers,...,-650.682759,27277.68,6.0,639.510000,No,Yes,Yes,No Information Available,No reason specified,1
36988,36988,29,F,21KSM8Y,Town,Basic Membership,2016-06-27,No,xxxxxxxx,Without Offers,...,-638.123421,11069.71,28.0,527.990000,Yes,No,No,Not Applicable,Poor Customer Service,1
36989,36989,23,F,XK1IM9H,NaN,Basic Membership,2016-09-11,Yes,CID3838,Gift Vouchers/Coupons,...,154.940000,38127.56,Error,680.470000,No,Yes,Yes,Unsolved,Poor Website,1
36990,36990,53,M,K6VTP1Z,Village,Platinum Membership,2017-06-15,No,xxxxxxxx,Gift Vouchers/Coupons,...,482.610000,2378.86,20.0,197.264414,Yes,Yes,No,Not Applicable,No reason specified,0
36991,36991,35,M,LBX0GLR,Town,Silver Membership,2015-10-23,No,xxxxxxxx,Gift Vouchers/Coupons,...,79.180000,2189.68,Error,719.970000,Yes,No,No,Not Applicable,Quality Customer Care,0

In [3]:
data.columns

Index(['Unnamed: 0', 'age', 'gender', 'security_no', 'region_category',
       'membership_category', 'joining_date', 'joined_through_referral',
       'referral_id', 'preferred_offer_types', 'medium_of_operation',
       'internet_option', 'last_visit_time', 'days_since_last_login',
       'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days',
       'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='str')

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    36992 non-null  int64
 1   age                           36992 non-null  int64
 2   gender                        36992 non-null  str
 3   security_no                   36992 non-null  str
 4   region_category               31564 non-null  str
 5   membership_category           36992 non-null  str
 6   joining_date                  36992 non-null  str
 7   joined_through_referral       36992 non-null  str
 8   referral_id                   36992 non-null  str
 9   preferred_offer_types         36704 non-null  str
 10  medium_of_operation           36992 non-null  str
 11  internet_option               36992 non-null  str
 12  last_visit_time               36992 non-null  str
 13  days_since_last_login         36992 non-null  int64
 14  avg_time_spent                36992 non-null  float64
 15  avg_transaction_value         36992 non-null  float64
 16  avg_frequency_login_days      36992 non-null  str
 17  points_in_wallet              33549 non-null  float64
 18  used_special_discount         36992 non-null  str
 19  offer_application_preference  36992 non-null  str
 20  past_complaint                36992 non-null  str
 21  complaint_status              36992 non-null  str
 22  feedback                      36992 non-null  str
 23  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(4), str(17)
memory usage: 6.8 MB

In [5]:
data.isnull().sum()

Unnamed: 0                         0
age                                0
gender                             0
security_no                        0
region_category                 5428
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types            288
medium_of_operation                0
internet_option                    0
last_visit_time                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
avg_frequency_login_days           0
points_in_wallet                3443
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
churn_risk_score                   0
dtype: int64

In [6]:
# 3 cols with nulls- region_category,prefered_offer_types,points_in_wallet
data['region_category'].value_counts()
# we cannot just fill it with the mode here since we cant be sure of the persons region,
# it might be inaccurate,which is not very helpful.
# not assuming sometimes is better than bad assumptions
# assigning all missing rows to the most common category (Town) may bias the distribution ,
# it may create fake patterns for the model to learn

region_category
Town       14128
City       12737
Village     4699
Name: count, dtype: int64

In [7]:
data['region_category'] = data['region_category'].fillna('Unknown')

In [8]:
# prefered_offer_types is not a numerical col as well hence same fill with unknown
data['preferred_offer_types'] = data['preferred_offer_types'].fillna('Unknown')

In [9]:
# numerical column, so use median since it is robust to outliers.
data['points_in_wallet'] = data['points_in_wallet'].fillna(data['points_in_wallet'].median())
# check 
data['preferred_offer_types'].value_counts()

preferred_offer_types
Gift Vouchers/Coupons       12349
Credit/Debit Card Offers    12274
Without Offers              12081
Unknown                       288
Name: count, dtype: int64

In [10]:
data['points_in_wallet'].value_counts()

points_in_wallet
697.620000     3446
705.070000        9
780.920000        8
760.540000        7
771.750000        7
               ...
1251.708596       1
1096.932079       1
242.979625        1
639.510000        1
197.264414        1
Name: count, Length: 23699, dtype: int64

In [11]:
data.isnull().sum()

Unnamed: 0                      0
age                             0
gender                          0
security_no                     0
region_category                 0
membership_category             0
joining_date                    0
joined_through_referral         0
referral_id                     0
preferred_offer_types           0
medium_of_operation             0
internet_option                 0
last_visit_time                 0
days_since_last_login           0
avg_time_spent                  0
avg_transaction_value           0
avg_frequency_login_days        0
points_in_wallet                0
used_special_discount           0
offer_application_preference    0
past_complaint                  0
complaint_status                0
feedback                        0
churn_risk_score                0
dtype: int64

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data['churn_risk_score'].value_counts()

churn_risk_score
1    20012
0    16980
Name: count, dtype: int64

In [14]:
# drop useless cols which dont play a role in model training
drop_cols = ['Unnamed: 0', 'security_no', 'referral_id']
data.drop(columns=drop_cols,inplace = True)

In [16]:
# next step must be handling data and time columns, as the model might confuse it for a string as its datatype is 'str'
# check joining_date,last_visit_time
data[['joining_date','last_visit_time']]

      joining_date last_visit_time
0       2017-08-17        16:08:02
1       2017-08-28        12:38:13
2       2016-11-11        22:53:21
3       2016-10-29        15:57:50
4       2017-09-12        15:46:44
...            ...             ...
36987   2017-09-21        04:14:05
36988   2016-06-27        23:18:31
36989   2016-09-11        03:50:25
36990   2017-06-15        09:50:03
36991   2015-10-23        01:39:52

[36992 rows x 2 columns]

In [20]:
data['joining_date']=pd.to_datetime(data['joining_date'],errors='coerce')
data['joining_date']

0       2017-08-17
1       2017-08-28
2       2016-11-11
3       2016-10-29
4       2017-09-12
           ...
36987   2017-09-21
36988   2016-06-27
36989   2016-09-11
36990   2017-06-15
36991   2015-10-23
Name: joining_date, Length: 36992, dtype: datetime64[us]

In [22]:
# getting the most recent date
reference_date = data['joining_date'].max()
reference_date

Timestamp('2017-12-31 00:00:00')

In [23]:
# feature engineering from joining_date
# questions to ask!!
# How long has the customer been with the company?
data['tenure_days'] = (reference_date - data['joining_date']).dt.days

In [24]:
data['joining_month'] = data['joining_date'].dt.month
data['joining_year'] = data['joining_date'].dt.year

In [26]:
data.drop(columns=['joining_date'], inplace=True)

In [28]:
# convert to datetime
data['last_visit_time'] = pd.to_datetime(data['last_visit_time'],format='%H:%M:%S', errors='coerce')

In [30]:
# since time itself is not that useful for the model to interpret, go ahead with the hour of the day
data['last_visit_hour'] = data['last_visit_time'].dt.hour

In [31]:
data.drop(columns=['last_visit_time'], inplace=True)

In [32]:
obj_cols = data.select_dtypes(include='object').columns.tolist()

for col in obj_cols:
    data[col] = data[col].astype(str).str.strip()
data.head()

C:\Users\Samhita Reddy\AppData\Local\Temp\ipykernel_32760\1115110402.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = data.select_dtypes(include='object').columns.tolist()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,...,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,tenure_days,joining_month,joining_year,last_visit_hour
0,18,F,Village,Platinum Membership,No,Gift Vouchers/Coupons,?,Wi-Fi,17,300.63,...,Yes,Yes,No,Not Applicable,Products always in Stock,0,136,8,2017,16
1,32,F,City,Premium Membership,?,Gift Vouchers/Coupons,Desktop,Mobile_Data,16,306.34,...,Yes,No,Yes,Solved,Quality Customer Care,0,125,8,2017,12
2,44,F,Town,No Membership,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,...,No,Yes,Yes,Solved in Follow-up,Poor Website,1,415,11,2016,22
3,37,M,City,No Membership,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,...,No,Yes,Yes,Unsolved,Poor Website,1,428,10,2016,15
4,31,F,City,No Membership,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,...,No,Yes,Yes,Solved,Poor Website,1,110,9,2017,15

In [33]:
# Feature Engineering from Existing Columns
#  Complaint-based features
data['complaint_status'].value_counts()

complaint_status
Not Applicable              18602
Unsolved                     4644
Solved                       4619
Solved in Follow-up          4577
No Information Available     4550
Name: count, dtype: int64

In [34]:
data['past_complaint'] = data['past_complaint'].astype(str).str.lower().str.strip()
data['complaint_status'] = data['complaint_status'].astype(str).str.lower().str.strip()

In [39]:
# find out complaints which are unresolved
resolved = ['solved', 'solved in follow up']

data['complaint_unresolved'] = (
    (data['past_complaint'] == 'yes') &
    (~data['complaint_status'].isin(resolved))
).astype(int)

In [ ]:
# converting yes,no columns into 1,0 for readability by the algorithm
# Referral flag
df['joined_through_referral_flag'] = df['joined_through_referral'].astype(str).str.lower().map({'yes': 1, 'no': 0})

# Special discount flag
df['used_special_discount_flag'] = df['used_special_discount'].astype(str).str.lower().map({'yes': 1, 'no': 0})

# Offer application preference flag
df['offer_application_preference_flag'] = df['offer_application_preference'].astype(str).str.lower().map({'yes': 1, 'no': 0})

# Inactivity flag
df['is_inactive_30plus'] = (df['days_since_last_login'] > 30).astype(int)